import React from 'react';
import { FlaskConical } from 'lucide-react';

interface ReportViewProps {
    title: string;
    date: string;
    params: { label: string; value: string | number }[];
    results: { label: string; value: string | number; highlight?: boolean }[];
    chartImage?: string; // Data URL of the captured chart
    insight: string;
}

export const ReportView = ({ title, date, params, results, chartImage, insight }: ReportViewProps) => {
    return (
        <div className="w-[210mm] min-h-[297mm] bg-white text-black p-[20mm] box-border relative font-sans leading-relaxed">
            {/* Header */}
            <header className="border-b-2 border-black pb-4 mb-8 flex justify-between items-end">
                <div>
                    <div className="flex items-center gap-2 font-bold text-2xl text-black tracking-tight mb-2">
                        <FlaskConical className="w-6 h-6" />
                        <span>Synthetic <span className="text-lime-600">DOE</span> Lab</span>
                    </div>
                    <div className="text-sm text-gray-500">AI-Powered Experimental Design & Analysis Platform</div>
                </div>
                <div className="text-right">
                    <h1 className="text-xl font-bold uppercase tracking-wide text-gray-800">Statistical Report</h1>
                    <div className="text-sm text-gray-500">{date}</div>
                </div>
            </header>

            {/* Title */}
            <section className="mb-10 text-center">
                <h2 className="text-3xl font-bold text-black mb-2">{title}</h2>
                <div className="h-1 w-20 bg-lime-500 mx-auto"></div>
            </section>

            {/* Parameters & Summary */}
            <section className="mb-8 p-6 bg-gray-50 rounded-xl border border-gray-200">
                <h3 className="text-lg font-bold border-l-4 border-gray-800 pl-3 mb-4 uppercase text-gray-700">Analysis Parameters</h3>
                <div className="grid grid-cols-2 gap-y-2 gap-x-8">
                    {params.map((p, i) => (
                        <div key={i} className="flex justify-between border-b border-gray-200 py-1">
                            <span className="text-gray-600 font-medium">{p.label}</span>
                            <span className="font-bold">{p.value}</span>
                        </div>
                    ))}
                </div>
            </section>

            {/* Key Results */}
            <section className="mb-8">
                <h3 className="text-lg font-bold border-l-4 border-lime-500 pl-3 mb-4 uppercase text-gray-700">Key Results</h3>
                <div className="grid grid-cols-3 gap-4">
                    {results.map((r, i) => (
                        <div key={i} className={`p-4 rounded-xl border ${r.highlight ? 'bg-lime-50 border-lime-200' : 'bg-white border-gray-200 shadow-sm'}`}>
                            <div className="text-sm text-gray-500 mb-1">{r.label}</div>
                            <div className={`text-2xl font-bold ${r.highlight ? 'text-lime-700' : 'text-black'}`}>
                                {r.value}
                            </div>
                        </div>
                    ))}
                </div>
            </section>

            {/* Visualization */}
            <section className="mb-8">
                <h3 className="text-lg font-bold border-l-4 border-purple-500 pl-3 mb-4 uppercase text-gray-700">Visualization</h3>
                <div className="border border-gray-200 rounded-xl p-2 bg-white flex justify-center items-center min-h-[300px]">
                    {chartImage ? (
                        <img src={chartImage} alt="Analysis Chart" className="max-w-full max-h-[400px] object-contain" />
                    ) : (
                        <div className="text-gray-400">Chart Image Not Available</div>
                    )}
                </div>
            </section>

            {/* Expert Insight */}
            <section className="mb-12">
                <h3 className="text-lg font-bold border-l-4 border-blue-500 pl-3 mb-4 uppercase text-gray-700">Expert Insight</h3>
                <div className="p-6 bg-blue-50 border border-blue-100 rounded-xl text-gray-800 leading-7 text-justify">
                    <strong className="text-blue-700 block mb-2">Analysis Interpretation:</strong>
                    {insight}
                </div>
            </section>

            {/* Footer */}
            <footer className="absolute bottom-[20mm] left-[20mm] right-[20mm] text-center border-t border-gray-200 pt-4 text-xs text-gray-400">
                <div className="flex justify-between">
                    <span>Generated by Synthetic DOE Lab v0.1</span>
                    <span>Confidential Research Data</span>
                </div>
            </footer>
        </div>
    );
};
